"""
memory_guard.py — Magnetic Field Prototype Visualizer · Resource Monitor
═════════════════════════════════════════════════════════════════════════════
Utility for monitoring system memory consumption, compressing field line
datasets, and purging temporary files generated by the visualizer pipeline.

Modes of operation:
  Default   — One-shot system report, dataset compression, and GC sweep.
  --watch   — Continuous polling mode; garbage collection is triggered
              automatically when RAM utilisation exceeds the critical threshold.
  --compress — Dataset compression only; no system monitoring.
  --purge   — Temporary file removal only.

Usage:
  python memory_guard.py                  one-shot report and cleanup
  python memory_guard.py --watch          continuous resource monitor (Ctrl+C to stop)
  python memory_guard.py --compress       compress magnetosphere_data.json only
  python memory_guard.py --purge          remove temporary files only
  python memory_guard.py --precision N    float decimal places in output (default: 3)
  python memory_guard.py --interval N     watch mode polling interval in seconds (default: 5)
"""

import argparse
import gc
import json
import math
import os
import shutil
import sys
import time
import tempfile
import glob
from pathlib import Path

# ── psutil is optional; basic GC remains available without it ─────────────
try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False

# ── Resource thresholds ───────────────────────────────────────────────────
RAM_WARN_PCT  = 70   # System RAM utilisation threshold for advisory notice [%]
RAM_CRIT_PCT  = 85   # System RAM utilisation threshold for automatic GC sweep [%]
CPU_WARN_PCT  = 80   # CPU utilisation advisory threshold [%]

# ── File paths ────────────────────────────────────────────────────────────
SCRIPT_DIR    = Path(__file__).parent
JSON_INPUT    = SCRIPT_DIR / "magnetosphere_data.json"
JSON_OUTPUT   = SCRIPT_DIR / "magnetosphere_data_mini.json"
PYCACHE_DIRS  = list(SCRIPT_DIR.rglob("__pycache__"))
TMPFILES_GLOB = str(SCRIPT_DIR / "tmp_*.json")

RESET  = "\033[0m"
RED    = "\033[91m"
YELLOW = "\033[93m"
GREEN  = "\033[92m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"


# ════════════════════════════════════════════════════════════════════════════
#  SYSTEM RESOURCE REPORTING
# ════════════════════════════════════════════════════════════════════════════
def get_system_stats() -> dict:
    """
    Retrieve current system memory and CPU utilisation via psutil.

    Returns a dict with key 'available' set to False if psutil is not installed.
    All memory values are returned in GB; utilisation values in percent.
    """
    if not HAS_PSUTIL:
        return {"available": False}

    vm   = psutil.virtual_memory()
    swap = psutil.swap_memory()
    cpu  = psutil.cpu_percent(interval=0.3)

    return {
        "available":    True,
        "ram_total_gb": vm.total / 1e9,
        "ram_used_gb":  vm.used  / 1e9,
        "ram_pct":      vm.percent,
        "ram_avail_gb": vm.available / 1e9,
        "swap_used_gb": swap.used  / 1e9,
        "swap_total_gb":swap.total / 1e9,
        "cpu_pct":      cpu,
    }


def color_pct(pct: float, warn: float, crit: float) -> str:
    """Return an ANSI-coloured percentage string: red if critical, yellow if warning."""
    if pct >= crit:  return f"{RED}{BOLD}{pct:.1f}%{RESET}"
    if pct >= warn:  return f"{YELLOW}{pct:.1f}%{RESET}"
    return f"{GREEN}{pct:.1f}%{RESET}"


def print_stats(stats: dict):
    """Render a formatted system resource panel to stdout."""
    if not stats["available"]:
        print(f"{YELLOW}psutil is not installed. "
              f"Install with: pip install psutil --break-system-packages{RESET}")
        print(f"  Python garbage collection sweep will proceed regardless.\n")
        return

    bar_len    = 20
    ram_filled = int(bar_len * stats["ram_pct"] / 100)
    ram_bar    = "█" * ram_filled + "░" * (bar_len - ram_filled)

    cpu_filled = int(bar_len * stats["cpu_pct"] / 100)
    cpu_bar    = "█" * cpu_filled + "░" * (bar_len - cpu_filled)

    print(f"\n{CYAN}{'━'*52}{RESET}")
    print(f"  {BOLD}SYSTEM RESOURCE STATUS{RESET}")
    print(f"{'━'*52}")
    print(f"  RAM  [{ram_bar}] {color_pct(stats['ram_pct'], RAM_WARN_PCT, RAM_CRIT_PCT)}"
          f"  {stats['ram_used_gb']:.1f} / {stats['ram_total_gb']:.1f} GB"
          f"  (available: {stats['ram_avail_gb']:.1f} GB)")
    print(f"  CPU  [{cpu_bar}] {color_pct(stats['cpu_pct'], CPU_WARN_PCT, 95)}")
    if stats["swap_total_gb"] > 0:
        print(f"  SWAP  {stats['swap_used_gb']:.2f} / {stats['swap_total_gb']:.1f} GB")
    print(f"{'━'*52}\n")


def gc_sweep():
    """
    Execute a full Python garbage collection sweep across all three generations.

    RSS memory before and after the sweep is sampled via psutil where available.
    Collected object count and approximate memory recovered are reported.
    """
    before = 0.0
    if HAS_PSUTIL:
        before = psutil.Process(os.getpid()).memory_info().rss / 1e6

    collected = gc.collect(generation=2)

    after = 0.0
    if HAS_PSUTIL:
        after = psutil.Process(os.getpid()).memory_info().rss / 1e6

    freed = max(0.0, before - after)
    print(f"  {GREEN}GC sweep complete: {collected} objects collected, "
          f"~{freed:.1f} MB recovered.{RESET}")


# ════════════════════════════════════════════════════════════════════════════
#  DATASET COMPRESSION
# ════════════════════════════════════════════════════════════════════════════
def compress_json(in_path: Path, out_path: Path, precision: int = 3) -> bool:
    """
    Reduce file size of a field line JSON dataset by truncating float precision
    and recomputing the grayscale index from stored intensity values.

    Compression strategy:
      1. Float coordinates and field vectors are rounded to `precision` decimal
         places (default 3), which is sufficient for sub-pixel visual accuracy.
      2. The `gray` field is recomputed from `intensity` and is not stored
         redundantly in the input; it is written fresh to the output.
      3. Compact JSON separators (no whitespace) are applied.

    At precision = 3, a typical reduction of 8–15% is observed relative to
    the default 4–5 decimal place output. Greater reductions are achievable
    at precision = 2, with negligible visual impact for scene-scale data.

    Parameters
    ----------
    in_path : Path
        Input JSON file (field line dataset).
    out_path : Path
        Destination path for the compressed output.
    precision : int
        Number of decimal places retained in floating-point fields.

    Returns
    -------
    bool : True on success, False if the input file is not found.
    """
    if not in_path.exists():
        print(f"  {RED}Input file not found: {in_path}{RESET}")
        return False

    in_size = in_path.stat().st_size
    print(f"  Input:  {in_path.name}  ({in_size/1024:.1f} KB, {in_size/1e6:.2f} MB)")

    print(f"  Loading...", end="", flush=True)
    with open(in_path) as f:
        data = json.load(f)

    # Filter metadata records before processing
    records = [p for p in data if p.get("source") != "meta"]
    print(f" {len(records)} field line records loaded.")

    # Point count ceiling is enforced on compression as a secondary check
    if len(records) > 5000:
        records = records[:5000]
        print(f"  {YELLOW}Dataset truncated to 5,000 records per hardware constraint.{RESET}")

    # Grayscale index is recomputed from stored intensity values
    intensities = [p.get("intensity", 0.0) for p in records]
    i_min = min(intensities)
    i_max = max(intensities)
    span  = max(i_max - i_min, 1e-9)

    print(f"  Compressing to {precision}-decimal float precision...")
    mini = []
    for p in records:
        norm = (p.get("intensity", 0.0) - i_min) / span
        norm = math.pow(max(0.0, min(1.0, norm)), 0.7)
        gray = int(round(norm * 255))

        mini.append({
            "x":         round(p["x"],         precision),
            "y":         round(p["y"],         precision),
            "z":         round(p["z"],         precision),
            "Bx":        round(p["Bx"],        precision),
            "By":        round(p["By"],        precision),
            "Bz":        round(p["Bz"],        precision),
            "intensity": round(p["intensity"], 2),
            "gray":      gray,
        })

    raw = json.dumps(mini, separators=(",", ":"))
    with open(out_path, "w") as f:
        f.write(raw)

    out_size = out_path.stat().st_size
    ratio    = (1 - out_size / in_size) * 100

    print(f"  {GREEN}Output: {out_path.name}  ({out_size/1024:.1f} KB)  "
          f"— {ratio:.0f}% reduction.{RESET}")
    return True


# ════════════════════════════════════════════════════════════════════════════
#  TEMPORARY FILE CLEANUP
# ════════════════════════════════════════════════════════════════════════════
def purge_temp_files():
    """
    Remove Python bytecode cache directories and scratch JSON files
    generated during pipeline execution.

    System /tmp entries matching the magnetosphere pattern and older than
    one hour are also removed. All removals are silent-on-failure to avoid
    interrupting the cleanup sequence.
    """
    freed   = 0
    removed = 0

    # Python bytecode cache directories (__pycache__)
    for cache_dir in list(SCRIPT_DIR.rglob("__pycache__")):
        try:
            size = sum(f.stat().st_size for f in cache_dir.rglob("*") if f.is_file())
            shutil.rmtree(cache_dir, ignore_errors=True)
            freed   += size
            removed += 1
        except Exception as e:
            print(f"  {YELLOW}Could not remove {cache_dir}: {e}{RESET}")

    # Scratch JSON files from the current working directory
    for tmp in glob.glob(TMPFILES_GLOB):
        try:
            sz = os.path.getsize(tmp)
            os.remove(tmp)
            freed   += sz
            removed += 1
        except Exception:
            pass

    # Stale visualizer files in the system temporary directory (>1 hour old)
    sys_tmp = Path(tempfile.gettempdir())
    for f in sys_tmp.glob("magnetosphere_*"):
        try:
            if time.time() - f.stat().st_mtime > 3600:
                f.unlink()
                removed += 1
        except Exception:
            pass

    print(f"  {GREEN}{removed} temporary items removed, ~{freed/1024:.0f} KB reclaimed.{RESET}")


# ════════════════════════════════════════════════════════════════════════════
#  CONTINUOUS MONITORING MODE
# ════════════════════════════════════════════════════════════════════════════
def watch_mode(interval: float = 5.0):
    """
    Poll system resources at the specified interval and trigger a GC sweep
    automatically when RAM utilisation exceeds RAM_CRIT_PCT.

    The trigger resets once utilisation returns below RAM_WARN_PCT to prevent
    repeated sweeps within a single elevated-usage period.

    Parameters
    ----------
    interval : float
        Polling interval in seconds.
    """
    print(f"\n{CYAN}Resource monitor active — polling every {interval} s  "
          f"(Ctrl+C to stop){RESET}\n")
    gc_triggered = False

    try:
        while True:
            os.system('clear' if os.name != 'nt' else 'cls')
            print(f"{BOLD}Magnetic Field Prototype Visualizer — Resource Monitor{RESET}"
                  f"  {time.strftime('%H:%M:%S')}")
            stats = get_system_stats()
            print_stats(stats)

            if stats.get("available"):
                ram = stats["ram_pct"]
                if ram >= RAM_CRIT_PCT and not gc_triggered:
                    print(f"  {RED}RAM utilisation critical ({ram:.1f}%). "
                          f"Initiating garbage collection sweep.{RESET}")
                    gc_sweep()
                    gc_triggered = True
                elif ram < RAM_WARN_PCT:
                    gc_triggered = False    # reset trigger for subsequent exceedances

                if ram >= RAM_WARN_PCT:
                    print(f"  {YELLOW}RAM utilisation elevated. Consider loading "
                          f"magnetosphere_data_mini.json for reduced memory footprint.{RESET}")
                else:
                    print(f"  {GREEN}System resources within nominal limits.{RESET}")

            time.sleep(interval)
    except KeyboardInterrupt:
        print(f"\n{CYAN}Resource monitor stopped.{RESET}")


# ════════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════
def main():
    parser = argparse.ArgumentParser(
        description="Magnetic Field Prototype Visualizer — Resource Monitor")
    parser.add_argument("--watch",     action="store_true",
                        help="Continuous resource monitoring mode")
    parser.add_argument("--compress",  action="store_true",
                        help="Dataset compression only")
    parser.add_argument("--purge",     action="store_true",
                        help="Temporary file removal only")
    parser.add_argument("--precision", type=int,   default=3,
                        help="Float decimal places in compressed output (default: 3)")
    parser.add_argument("--interval",  type=float, default=5.0,
                        help="Watch mode polling interval in seconds (default: 5)")
    args = parser.parse_args()

    print(f"\n{BOLD}{CYAN}Magnetic Field Prototype Visualizer — Resource Monitor{RESET}")

    if args.watch:
        watch_mode(args.interval)
        return

    # ── One-shot system report ────────────────────────────────────────────
    if not HAS_PSUTIL:
        print(f"\n{YELLOW}psutil is not installed. Detailed resource monitoring is unavailable.{RESET}")
        print(f"  Install with: pip install psutil --break-system-packages\n")
    else:
        stats = get_system_stats()
        print_stats(stats)

    # ── Dataset compression ───────────────────────────────────────────────
    if not args.purge:
        print(f"\n{BOLD}[1/2] DATASET COMPRESSION{RESET}")
        if JSON_INPUT.exists():
            compress_json(JSON_INPUT, JSON_OUTPUT, precision=args.precision)
        else:
            print(f"  {YELLOW}Input file not found: {JSON_INPUT.name}{RESET}")
            print(f"  Run generate_magnetosphere.py to produce the dataset.")

    # ── Temporary file removal ────────────────────────────────────────────
    print(f"\n{BOLD}[2/2] TEMPORARY FILE CLEANUP{RESET}")
    purge_temp_files()

    # ── Garbage collection sweep ──────────────────────────────────────────
    print(f"\n{BOLD}[+] GARBAGE COLLECTION{RESET}")
    gc_sweep()

    print(f"\n{GREEN}{BOLD}Process complete. Resources cleared.{RESET}\n")

    if not args.purge and JSON_OUTPUT.exists():
        print(f"  {JSON_OUTPUT.name} is available for reduced-footprint loading.")
    print()


if __name__ == "__main__":
    main()
